name: Build and Deploy

on:
  push:
    tags: ["v[0-9].[0-9]+.[0-9]+"]
    branches:
      - "development"
      - "main"

jobs:
  packer:
    runs-on: ubuntu-latest
    name: Run Packer
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: "latest"

      - name: Run `packer init`
        id: init
        working-directory: ./ubuntu-20.04-amd64
        run: "packer init ."

      - name: Run `packer validate`
        id: validate
        working-directory: ./ubuntu-20.04-amd64
        run: "packer validate -var-file=./variables.development.pkrvars.hcl ."

      # - name: Run `packer deploy`
      #   id: validate
      #   working-directory: ./ubuntu-20.04-amd64
      #   run: "packer build -var-file=./variables.development.pkrvars.hcl ."
    