name: Build and deploy images to proxmox pineapple cluster

on:
  push:
    tags: ["v[0-9].[0-9]+.[0-9]+"]
    branches:
      - "main"

jobs:
  packer:
    runs-on: ubuntu-latest
    name: Run packer init, validate and build
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: ZeroTier
        uses: zerotier/github-action@v1.0.1
        with:
          network_id: ${{ secrets.ZEROTIER_NETWORK_ID }}
          auth_token: ${{ secrets.ZEROTIER_CENTRAL_TOKEN }}
          api_url: ${{ secrets.ZEROTIER_API_URL }}

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: "latest"

      - name: Run `packer init`
        id: init
        working-directory: ./ubuntu-20.04-amd64
        run: "packer init ."

      - name: Run `packer validate`
        id: validate
        working-directory: ./ubuntu-20.04-amd64
        run: "packer validate -var-file=./variables.backup.pkrvars.hcl ."
        env:
          PKR_VAR_proxmox_host: ${{ vars.PROXMOX_HOST_BACKUP }}
          PKR_VAR_proxmox_username: ${{ vars.PROXMOX_USERNAME }}
          PKR_VAR_proxmox_password: ${{ secrets.PROXMOX_PASSWORD_BACKUP }}

      # - name: Run `packer build`
      #   id: build
      #   working-directory: ./ubuntu-20.04-amd64
      #   run: "packer build -var-file=./variables.backup.pkrvars.hcl ."
      #   env:
      #     PKR_VAR_proxmox_host: ${{ vars.PROXMOX_HOST_BACKUP }}
      #     PKR_VAR_proxmox_username: ${{ vars.PROXMOX_USERNAME }}
      #     PKR_VAR_proxmox_password: ${{ secrets.PROXMOX_PASSWORD_BACKUP }}
    