name: Deploy to pineapple cluster

on:
  push:
    tags: ["v[0-9].[0-9]+.[0-9]+"]
    branches:
      - "main"

jobs:
  packer:
    runs-on: ubuntu-latest
    environment: pineapple
    name: Run packer init, validate and build
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # - name: Import Secrets
      #   id: import-secrets
      #   uses: hashicorp/vault-action@v2
      #   with:
      #     url: ${{ secrets.VAULT_ADDR }}
      #     tlsSkipVerify: true
      #     role: github-runner-jakoberpf
      #     method: jwt
      #     secrets: |
      #         CICD/global/ssh/automation PRIVAT_KEY_RSA_PEM | SSH_PRIVAT_KEY ;

      - name: Setup SSH Key
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa

      - name: ZeroTier
        uses: jakoberpf/github-action-zerotier@main # zerotier/github-action@v1.0.1
        with:
          network_id: ${{ secrets.ZEROTIER_NETWORK_ID }}
          auth_token: ${{ secrets.ZEROTIER_CENTRAL_TOKEN }}
          api_url: ${{ secrets.ZEROTIER_API_URL }}

      - name: Ping cluster hosts
        run: |
          ping 172.30.119.190

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: "latest"

      - name: Run `packer init`
        id: init-alpine
        working-directory: ./alpine-3-amd64
        run: "packer init ."

      - name: Run `packer validate`
        id: validate-alpine
        working-directory: ./alpine-3-amd64
        run: "packer validate -var-file=./variables.pineapple.pkrvars.hcl ."
        env:
          # PKR_VAR_proxmox_host: ${{ vars.PROXMOX_HOST }}
          PKR_VAR_proxmox_username: ${{ vars.PROXMOX_USERNAME }}
          PKR_VAR_proxmox_password: ${{ secrets.PROXMOX_PASSWORD }}

      - name: Run `packer build`
        id: build-alpine
        working-directory: ./alpine-3-amd64
        run: "packer build -var-file=./variables.pineapple.pkrvars.hcl ."
        env:
          # PKR_VAR_proxmox_host: ${{ vars.PROXMOX_HOST }}
          PKR_VAR_proxmox_username: ${{ vars.PROXMOX_USERNAME }}
          PKR_VAR_proxmox_password: ${{ secrets.PROXMOX_PASSWORD }}

      - name: Run `packer init`
        id: init-ubuntu
        working-directory: ./ubuntu-20.04-amd64
        run: "packer init ."

      # - name: Run `packer validate`
      #   id: validate-ubuntu
      #   working-directory: ./ubuntu-20.04-amd64
      #   run: "packer validate -var-file=./variables.backup.pkrvars.hcl ."
      #   env:
      #     PKR_VAR_proxmox_host: ${{ vars.PROXMOX_HOST }}
      #     PKR_VAR_proxmox_username: ${{ vars.PROXMOX_USERNAME }}
      #     PKR_VAR_proxmox_password: ${{ secrets.PROXMOX_PASSWORD_BACKUP }}

      # - name: Run `packer build`
      #   id: build-ubuntu
      #   working-directory: ./ubuntu-20.04-amd64
      #   run: "packer build -var-file=./variables.backup.pkrvars.hcl ."
      #   env:
      #     PKR_VAR_proxmox_host: ${{ vars.PROXMOX_HOST }}
      #     PKR_VAR_proxmox_username: ${{ vars.PROXMOX_USERNAME }}
      #     PKR_VAR_proxmox_password: ${{ secrets.PROXMOX_PASSWORD_BACKUP }}
    