name: Build and deploy images to proxmox mango cluster

on:
  push:
    tags: ["v[0-9].[0-9]+.[0-9]+"]
    branches:
      - "development"
      - "main"

jobs:
  packer:
    runs-on: ubuntu-latest
    environment: mango
    name: Run packer init, validate and build
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: perform token run
        run: |
          echo $(curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=jakoberpf" | base64)

      - name: Import Secrets
        id: import-secrets
        uses: hashicorp/vault-action@v2
        with:
          url: ${{ secrets.VAULT_ADDR }}
          tlsSkipVerify: true
          role: github-runner-jakoberpf
          # path: jwt-github
          method: jwt
          jwtGithubAudience: repository
          secrets: |
              CICD/global/ssh/automation PRIVAT_KEY_RSA_PEM | SSH_PRIVAT_KEY ;
              CICD/global/ssh/automation PUBLIC_KEY_SSH | SSH_PUBLIC_KEY ;

      - name: ZeroTier
        uses: zerotier/github-action@v1.0.1
        with:
          network_id: ${{ secrets.ZEROTIER_NETWORK_ID }}
          auth_token: ${{ secrets.ZEROTIER_CENTRAL_TOKEN }}
          api_url: ${{ secrets.ZEROTIER_API_URL }}

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: "latest"

      - name: Run `packer init`
        id: init
        working-directory: ./ubuntu-20.04-amd64
        run: "packer init ."

      - name: Run `packer validate`
        id: validate
        working-directory: ./ubuntu-20.04-amd64
        run: "packer validate -var-file=./variables.development.pkrvars.hcl ."
        env:
          PKR_VAR_proxmox_host: ${{ vars.PROXMOX_HOST_DEVELOPMENT }}
          PKR_VAR_proxmox_username: ${{ vars.PROXMOX_USERNAME }}
          PKR_VAR_proxmox_password: ${{ secrets.PROXMOX_PASSWORD_DEVELOPMENT }}

      - name: Run `packer build`
        id: build
        working-directory: ./ubuntu-20.04-amd64
        run: "packer build -var-file=./variables.development.pkrvars.hcl ."
        env:
          PKR_VAR_proxmox_host: ${{ vars.PROXMOX_HOST_DEVELOPMENT }}
          PKR_VAR_proxmox_username: ${{ vars.PROXMOX_USERNAME }}
          PKR_VAR_proxmox_password: ${{ secrets.PROXMOX_PASSWORD_DEVELOPMENT }}
    